/**
 * disposableEmailBlocklist.js
 * Local blocklist of known temp/disposable email domains.
 * Applied on both backend (Node.js) and exported for use in frontend validation.
 */

const BLOCKED_DOMAINS = new Set([
    // ── Top abused disposable providers ──────────────────────────────────────
    'mailinator.com', 'guerrillamail.com', 'guerrillamail.info', 'guerrillamail.net',
    'guerrillamail.org', 'guerrillamail.biz', 'grr.la', 'guerrillamailblock.com',
    'tempmail.com', 'temp-mail.org', 'temp-mail.io', 'tempmail.net',
    'yopmail.com', 'yopmail.fr', 'cool.fr.nf', 'jetable.fr.nf', 'nospam.ze.tc',
    'nomail.xl.cx', 'mega.zik.dj', 'speed.1s.fr', 'courriel.fr.nf',
    '10minutemail.com', '10minutemail.net', '10minutemail.org', '10minutemail.de',
    '10minutemail.ru', '10minutemail.cf', '10minutemail.ga', '10minutemail.gq',
    '10minutemail.ml', '10minemail.com',
    'throwam.com', 'throwam.net', 'trashmail.com', 'trashmail.at', 'trashmail.io',
    'trashmail.me', 'trashmail.net', 'trashmail.org', 'trashmail.xyz', 'trashmail.de',
    'dispostable.com', 'mailnull.com', 'maildrop.cc', 'sharklasers.com',
    'spam4.me', 'getnada.com', 'fakeinbox.com', 'throwaway.email',
    'tempr.email', 'mailexpire.com', 'spamgourmet.com', 'moakt.com',
    'mintemail.com', 'emailondeck.com', 'tempinbox.com', 'sofimail.com',
    'binkmail.com', 'mailzilla.org', 'mailzilla.com',
    'mailnesia.com', 'spamevader.com', 'tempemail.net',
    // ── Guerrilla Mail variants ────────────────────────────────────────────────
    'spam4.me', 'grr.la', 'guerrillamail.biz', 'spam4.me', 'grr.la',
    // ── Fake/spam domains ─────────────────────────────────────────────────────
    'notmailinator.com', 'mailmetrash.com', 'jnxjn.com', 'trashdevil.com',
    'trashdevil.de', 'trbvm.com', 'incognitomail.com', 'anonymbox.com',
    'nwldx.com', 'spamfree24.org', 'spamfree24.de', 'spamfree24.eu',
    'spamfree24.info', 'trashmail.fr', 'yepmail.net', 'keepmymail.com',
    'pookmail.com', 'harakirimail.com', 'mail.mezimages.net',
    'zippymail.info', 'oneoffmail.com', 'mail2trash.com', 'spaml.com',
    'dingbone.com', 'junk1.tk', 'junk.me', 'mailseal.de',
    'mailscrap.com', 'mailblocks.com', 'crazymailing.com', 'rppkn.com',
    'discard.email', 'discardmail.com', 'discardmail.de', 'spammotel.com',
    'spammotel.info', 'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
    'nervmich.net', 'nervtmich.net', 'schafmail.de', 'spamkill.info',
    'spamhereplease.com', 'trash-mail.at', 'trash-mail.com', 'trash-mail.io',
    '33mail.com', 'anonaddy.com', 'spamgourmet.net', 'spamgourmet.org',
    'tempomail.fr', 'temporaryemail.net', 'temporaryinbox.com',
    'temptemp.email', 'throwam.com', 'throwmailaway.com', 'emailtemporal.org',
    'filzmail.com', 'filzmail.de', 'meltmail.com', 'mailnew.com',
    'inboxsss.com', 'despam.it', 'spamtrap.ro', 'gishpuppy.com',
    'mailbucket.org', 'maileater.com', 'byom.de', 'fakedemail.com',
    'fakemailgenerator.com', 'fakemailz.com', 'fakemail.net',
    'anonymail.dk', 'anonymailhub.com', 'beefmilk.com',
    'burnthespam.info', 'clashatclans.com', 'clrmail.com',
    'comsafe-mail.net', 'cool.fr.nf', 'dacoolest.com', 'dandikmail.com',
    'df.sought.com', 'digitalsanctuary.com', 'dingbone.com',
    'donemail.ru', 'e4ward.com', 'email60.com', 'emaildienst.de',
    'emailias.com', 'emailinfive.com', 'emailisvalid.com', 'emailpinoy.com',
    'emailproxsy.com', 'emailsensei.com', 'emailtemporanea.com',
    'emailxy.com', 'ephemail.net', 'etranquil.net', 'exdonuts.com',
    'explodemail.com', 'eyepaste.com', 'fakemailz.com', 'fantasymail.de',
    'fastacura.com', 'fastchevy.com', 'fastemails.us', 'filzmail.com',
    'fleckens.hu', 'fnmail.com', 'freundin.ru', 'fux0ringduh.com',
    'garbagemail.org', 'getonemail.com', 'getonemail.net',
    'girlmeetsgirl.com', 'google.com.de', 'gowikibooks.com',
    'gowikicampus.com', 'gowikicars.com', 'gowikifilms.com',
    'gowikigames.com', 'gowikimusic.com', 'gowikinetwork.com',
    'gowikitravel.com', 'gowikitv.com', 'grandmasmail.com',
    'great-host.in', 'guerillamail.biz', 'guerillamail.com',
    'guerillamail.de', 'guerillamail.info', 'guerillamail.net',
    'guerillamail.org', 'h.mintemail.com', 'hailmail.net',
    'herp.in', 'hidemail.de', 'hidzz.com', 'hochsitze.com',
    'hotpop.com', 'hulapla.de', 'iheartspam.org', 'ilovespam.com',
    'jetable.com', 'jetable.net', 'jetable.org', 'jnxjn.com',
    'jourrapide.com', 'jsrsolutions.com', 'junk1.tk',
    'kasmail.com', 'kaspop.com', 'keepmymail.com', 'killmail.com',
    'klzlk.com', 'koszmail.pl', 'kurzepost.de', 'lazyinbox.com',
    'letthemeatspam.com', 'lol.ovpn.to', 'lolfreak.net',
    'makemetheking.com', 'mbx.cc', 'meinspamschutz.de',
    'melt-mail.com', 'mos.ru', 'mosesandmoses.com', 'msgsafe.io',
    'mt2009.com', 'mt2014.com', 'mt2015.com', 'mx0.wwwav.name',
    'myspaceinc.com', 'myspaceinc.net', 'myspaceinc.org',
    'no-spam.ws', 'noblepioneer.com', 'noclickemail.com', 'nomail.pw',
    'nomorespamemails.com', 'nospam.ze.tc', 'nospam4.us', 'nospamthanks.info',
    'notmailinator.com', 'nowmymail.com', 'ntlhelp.net',
    'objectmail.com', 'obobbo.com', 'onewaymail.com', 'oopi.org',
    'ovpn.to', 'owlpic.com', 'pancakemail.com', 'pimpedupmyspace.com',
    'piratelove.net', 'plexolan.de', 'pm.me', 'pookemail.com',
    'prtnx.com', 'quickinbox.com', 'rcpt.at', 'rebuildener.org',
    'renraku.in', 'rhyta.com', 'rklips.com', 'rmqkr.net',
    'royal.net', 's0ny.net', 'safe-mail.net', 'safetymail.info',
    'safetypost.de', 'sandelf.de', 'schacktelefonare.se', 'sendspamhere.com',
    'shieldedmail.com', 'shiftmail.com', 'sibmail.com', 'sinnlos-mail.de',
    'skeefmail.com', 'slopsbox.com', 'smellfear.com', 'snakemail.com',
    'sneakemail.com', 'snkmail.com', 'sofort-mail.de', 'sogetthis.com',
    'sosmokearette.com', 'spamavert.com', 'spambob.com', 'spambob.net',
    'spambob.org', 'spambog.com', 'spambog.de', 'spambog.ru', 'spambooger.com',
    'spamcowboy.com', 'spamcowboy.net', 'spamcowboy.org', 'spamday.com',
    'spamex.com', 'spamfired.com', 'spamfree.eu', 'spamgone.com',
    'spamherelots.com', 'spamhole.com', 'spamify.com', 'spaminator.de',
    'spammail.me', 'spammer.fails', 'spams.adamas.ai',
    'spamspot.com', 'spamstack.net', 'spamthis.co.uk', 'spamthisplease.com',
    'spamtrail.com', 'speed.1s.fr', 'supermailer.jp', 'superrito.com',
    'suremail.info', 'sweetxxx.de', 'tafmail.com', 'tagyourself.com',
    'teewars.org', 'tempalias.com', 'tempail.com', 'tempalias.com',
    'tempe-mail.com', 'tempemailer.com', 'temporaryemail.us',
    'temporaryforwarding.com', 'tempsky.com', 'thanksnospam.com',
    'thecloudindex.com', 'the-fastest.net', 'theglobe.com',
    'thelimestones.com', 'thisisnotmyrealemail.com', 'throwam.com',
    'tilien.com', 'tmailinator.com',
    'toiea.com', 'trbvm.com', 'turual.com', 'tvchd.com',
    'twinmail.de', 'tyldd.com', 'ubm.md', 'ucupdong.ml',
    'uggsrock.com', 'umail.net', 'upliftnow.com', 'uplipht.com',
    'uroid.com', 'us.af', 'veryrealemail.com', 'vidchart.com',
    'viditag.com', 'viewcastmedia.com', 'viewcastmedia.net',
    'viewcastmedia.org', 'viralplays.com', 'vomoto.com',
    'wilemail.com', 'willhackforfood.biz', 'willselfdestruct.com',
    'wuzupmail.net', 'xagloo.com', 'xblmail.com', 'xemaps.com',
    'xents.com', 'xmaily.com', 'xoxy.net', 'xww.ro', 'xxolocanto.us',
    'xyz.am', 'yapped.net', 'yeah.net', 'yep.it', 'yert.ye.vc',
    'yodx.ro', 'yourdomain.com', 'ypmail.webarnak.fr.eu.org',
    'yuurok.com', 'z0d.eu', 'zehnminutenmail.de', 'zoemail.net',
    'zoemail.org', 'zomg.info', 'zxcv.com', 'zxcvbnm.com',
]);

/**
 * Returns true if the email domain is disposable/temp.
 * Safe to call on both Node.js (backend) and in browser (frontend copy).
 */
function isDisposableEmail(email) {
    if (!email || typeof email !== 'string') return false;
    const domain = email.split('@')[1]?.toLowerCase()?.trim();
    if (!domain) return false;
    return BLOCKED_DOMAINS.has(domain);
}

module.exports = { isDisposableEmail, BLOCKED_DOMAINS };
